vim.o.autoindent = true
vim.o.autoread = true
vim.o.background = 'dark'
vim.o.backspace = 'start,eol,indent'
vim.o.backup = false
vim.o.clipboard = 'unnamedplus'
vim.o.colorcolumn = '+1'
vim.o.compatible = false
vim.o.copyindent = true
vim.o.cursorcolumn = true
vim.o.cursorline = true
vim.o.hidden = true
vim.o.hlsearch = true
vim.o.ignorecase = true
vim.o.ignorecase = true
vim.o.incsearch = true
vim.o.linebreak = false
vim.o.list = true
vim.o.matchtime = 3
vim.o.mouse = 'a'
vim.o.number = true
vim.o.paste = false
-- vim.opt.expandtab = true
-- vim.opt.fillchars = { vert = '#' }
-- vim.opt.listchars = { tab = '.', eol = '¬' }
-- vim.opt.match_paren = true
-- vim.opt.showtabline = 2
-- vim.opt.softtabstop = 2
-- vim.opt.tabstop = 2
-- vim.opt.t_co = 256
vim.opt.wildignore = {'*.swp', '*.bak', '*.pyc', '*.class'}
vim.o.relativenumber = true
vim.o.ruler = true
vim.o.shiftwidth = 2
vim.o.showmatch = true
vim.o.smartcase = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.startofline = false
vim.o.termguicolors = true
vim.o.textwidth = 80
vim.o.updatetime = 100
vim.o.wildmenu = true
vim.o.wrap = false
vim.o.writebackup = false
vim.wo.number = true
