#!/usr/bin/env zsh

# info: encrypts files using age.
# https://github.com/FiloSottile/age

recipients="${HOME}/.age/age-recipients"

[[ ! -f "${recipients}" ]] \
  && print -P "%F{red}${recipients} not found.%F{reset}\n" \
  && exit 1

single-encrypt() {
  target="${1}"
  age --encrypt \
    -R "${recipients}" \
    -o "${target}.age" "${target}"
  print -P -n "🔐%F{green}Encrypted to ${target}.age %F{reset}\n"
}

if [ -n "${1}" ]; then 
  [ -f "${1}" ] && single-encrypt "${1}"
else
  echo "No file given."
  echo "Press [ENTER] to encrypt all files in directory."
  echo "(ctrl+c to abort)"
  read
  for i in "$(find . -maxdepth 1 -type f | grep -v -E ".age$")"; do
    single-encrypt "${i}"
  done
fi
