#!/usr/bin/env bash

# info: encrypts files using age.
# https://github.com/FiloSottile/age

recipients="${HOME}/.age/age-recipients"

[[ ! -f "${recipients}" ]] \
  && echo "${recipients} not found." \
  && exit 1

single-encrypt() {
  target="${1}"
  age --encrypt \
    -R "${recipients}" \
    -o "${target}.age" "${target}"
  echo "🔐 Encrypted to ${target}.age"
}

if [ -n "${1}" ]; then 
  single-encrypt "${1}"
else
  echo "No file given."
  echo "Press [ENTER] to encrypt all files in directory."
  echo "(ctrl+c to abort)"
  read
  for i in "$(find . -maxdepth 1 -type f | grep -v -E ".age$")"; do
    single-encrypt "${i}"
  done
fi
