#!/usr/bin/env bash

BOOKMARKS_FILE="${HOME}/Nextcloud/40_Documents/bookmarks.txt"

add_bookmark() {
  if [ "${XDG_BACKEND}" == "wayland" ]; then
    bookmark=$(wl-copy --format plain-text)
  else
    bookmark=$(xclip -o)
  fi

  if grep -q "^$bookmark$" "$BOOKMARKS_FILE"; then
    notify-send "Bookmark Exists" "Bookmark '$bookmark' already exists."
  else
    echo "${bookmark}" >> ${BOOKMARKS_FILE}
    notify-send "Bookmark Added" "${bookmark}"
  fi
}

insert_bookmark() {
  if [ "${XDG_BACKEND}" == "wayland" ]; then
    exit 1
  else
    xdotool type $(cat "${BOOKMARKS_FILE}" | grep -v '^#' | rofi -dmenu -p "Select snippet to insert:" | cut -f1 -d' ')
  fi
}

case "$1" in
    add)
        add_bookmark
        ;;
    insert)
        insert_bookmark
        ;;
    *)
        kitty --class bookmarks -e vim $BOOKMARKS_FILE
        ;;
esac
