#!/usr/bin/env bash

# clipboard review in rofi

if [ "${XDG_BACKEND}" == "wayland" ]; then
  cliphist list | rofi -dmenu | cliphist decode | wl-copy
else
  cliphist list | rofi -dmenu | cliphist decode | xclip -i -selection clipboard
fi

notify-send "  Copied to clipboard" -u normal
