#!/usr/bin/env zsh

notes_dir=${NOTES_DIR:-$HOME/Documents/Notes}
ds=$(date +%Y-%m-%d)
note="${notes_dir}/${ds}.md"

mkdir -p "${notes_dir}"
find "${notes_dir}" -type f -name "*.md" -size 0 -delete

if [ ! -f "${note}" ]; then
  echo "# ${ds}" > ${note}
fi

nvim -c "norm Go" \
  -c "norm Go- $(date +%H:%M)" \
  -c "norm zz" \
  -c "norm Go  -  " \
  -c "startinsert" "${note}"
