#!/usr/bin/env zsh

set -e

mkdir -p ~/VM
vm_file="${HOME}/VM/debian-12-nocloud-amd64.qcow2"

if [ ! -f "${vm_file}" ]; then
  echo "downloading debian..."
  wget -P "${HOME}/VM" https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.qcow2
fi

print -P -n "%F{green} ● loading ${vm_file} %F{reset}\n"

# default user=root password=""
qemu-system-x86_64 \
  -enable-kvm \
  -m 4096M \
  -hda ${HOME}/VM/debian-12-nocloud-amd64.qcow2 \
  -net nic,model=virtio \
  -net user,hostfwd=tcp::5022-:22
