#!/usr/bin/env zsh
#
# dependencies:
# - https://github.com/raghur/mermaid-filter

md=$1
target=$(dirname "${md}")/pdf
output="$(basename "${md}").pdf"

mkdir -p ${target}

pandoc \
  --pdf-engine=tectonic \
  -V "geometry:margin=1in" \
  "${md}" -o "${target}/${output}"

xdg-open "${target}/${output}"
