#! /usr/bin/env bash

PREFIX="${PASSWORD_STORE_DIR:-$HOME/.password-store}"
FZF_DEFAULT_OPTS=""

[[ ! ${1} ]] && cmd="show"
name="$(find "$PREFIX" -type f -name '*.gpg' | \
  sed -e "s|$PREFIX/||" -e 's|\.gpg$||' | \
  fzf-tmux --prompt="pass ${cmd} " --height 40% --reverse --no-multi)"
set -xe
gopass --nosync "${@}" "$name"
exit 0
