#!/usr/bin/env bash

[[ $1 ]] || exit 1
p=$(wget -T2 -qO- https://blockchain.info/ticker | jq .USD.last)

if [[ "${1}" == *"."* ]]; then
  btc="${1}"
  sats=$(echo "print((${1}*100000000))" | python3)
else
  sats="${1}"
  btc=$(echo "print('{0:.08f}'.format(${sats}/100000000))" | python3)

fi

echo "${sats} sats"
echo "${btc} btc"
[[ "${p}" ]] && { 
  usd=$(echo "print('{0:.02f}'.format(${btc}*${p}))" | python3)
  echo "\$$usd (@\$${p})"
};
