#! /usr/bin/env bash

dir="${HOME}/Downloads/screenshots"
file="${dir}/screenshot_$(date +%s).jpg"
mkdir -p "${dir}"

export DISPLAY=:0

if [ "$XDG_SESSION_TYPE" != "wayland" ]; then
  # imagemagick command to select area on screen and take screenshot saved to file
  import "${file}" 
  # open dir
  xdg-open "${dir}" &
  # copy to clipboard
  xclip -selection clipboard -t image/png -i "${file}"
else
  grim -l 0 -g "$(slurp)" "${file}"
  wl-copy -t image/png < "${file}"
fi

notify-send "📋 copied ${file}"
