#!/usr/bin/env bash
set -e

# info: connects to proxmox VMs via SPICE on virt-viewer

# Set auth options
USERNAME="$(pass homelab/proxmox/user01 | grep login | awk '{print $2}')@pve"
PASSWORD="$(pass homelab/proxmox/user01 | head -n1)"

# Set VM ID from the first and only argument
VMID="$1"

# Set Node
# This must either be a DNS address or name of the node in the cluster
NODE="proxmox1"

# Proxy equals node if node is a DNS address
# Otherwise, you need to set the IP address of the node here
PROXY=$(pass show homelab/proxmox/user01 | grep node | awk '{print $2}')

#The rest of the script originated from a Proxmox example

#Strip the DNS name to get the node name
NODE="${NODE%%\.*}"

echo "[*] Authenticating to ${PROXY}..."

#Authenticate to the API and get a ticket and CSRF token
DATA="$(curl -f -s -S -k --data-urlencode "username=$USERNAME" \
  --data-urlencode "password=$PASSWORD" \
  "https://$PROXY:8006/api2/json/access/ticket")"

echo "[*] AUTH OK"

#Extract the ticket an CSRF token from the returned data
TICKET="${DATA//\"/}"
TICKET="${TICKET##*ticket:}"
TICKET="${TICKET%%,*}"
TICKET="${TICKET%%\}*}"

CSRF="${DATA//\"/}"
CSRF="${CSRF##*CSRFPreventionToken:}"
CSRF="${CSRF%%,*}"
CSRF="${CSRF%%\}*}"

#Request a SPICE config file from the API
# curl -f -s -S -k -b "PVEAuthCookie=$TICKET" -H "CSRFPreventionToken: $CSRF" "https://$PROXY:8006/api2/spiceconfig/nodes/$NODE/qemu/$VMID/spiceproxy" -X POST > spiceproxy
curl -f -s -S -k -b "PVEAuthCookie=$TICKET" -H "CSRFPreventionToken: $CSRF" "https://$PROXY:8006/api2/spiceconfig/nodes/$NODE/qemu/$VMID/spiceproxy" -X POST -d "proxy=$PROXY" > spiceproxy

echo "[*] Connecting..."

# Launch remote-viewer with spiceproxy file, in full screen mode
remote-viewer -f spiceproxy &
