#!/usr/bin/env bash

# info: sometimes yubikey stops working and only gets fixed when pcscd is killed

pid=$(pgrep pcscd)

if [ -n "${pid}" ]; then
  echo "● Killing pcscd process ${pid}..."
  sudo kill -9 $(pgrep pcscd)
else
  echo "No pcscd process detected."
fi

sleep 5
